### ISSUE TITLE
Webhook authorization

### ISSUE THREAD

**Issue by dsbatov** [yarbshk/bitrix24-python3-client#11]
Hello. As it is said in your readme, I don't need to authorize in any way if I use only webhooks. But I tried to write a simple one, and it keeps coming back with error 401 (unauthorized). Can you help me with that?

**Comment by yarbshk** [comment]
hi @dsbatov ! can you show a code snippet describing how you send a request?

**Comment by dsbatov** [comment]
sure, but it is simply the copy of your code in readme

from pybitrix24 import Bitrix24

bx24 = Bitrix24('consiliummedicum.bitrix24.ru')
bx24.call_webhook('pu0qtn08t3e12eby', 'crm.lead.fields', {'ID': 17})
{'result': {...}}

**Comment by yarbshk** [comment]
@dsbatov thanks for your feedback! i missed that user id is required when making requests. just add appropriate argument during initialization of Bitrix24 like follows:

```
bx24 = Bitrix24('consiliummedicum.bitrix24.ru', user_id=1)
```

i'll add default user id in future versions

**Comment by dsbatov** [comment]
thanks, it worked!
