### ISSUE TITLE
Re-writing multiple fields in crm.lead

### ISSUE THREAD

**Issue by sbatov** [yarbshk/bitrix24-python3-client#14]
Colleagues, kindly advise the way implement the following:
Need to re-write the 'EMAIL' field in crm.lead
Ideally - update - replacement of the whole list of email values to the new one.
Maybe - in two steps: delete the whole list of values and then add a new one

the following code only adds the values to the list:
bx24.call_webhook('***********', 'crm.lead.update', 
	{
		'ID': tmpID, 
			'fields': 'EMAIL':{'ID':'','VALUE_TYPE': 'WORK', 'VALUE': 'lalala@anydomain.ru', 'TYPE_ID': 'EMAIL'}, 
			'params': { "REGISTER_SONET_EVENT": "Y"}
	}
)

And the folwing code does nothing:
bx24.call_webhook('***********', 'crm.lead.update', 
	{
		'ID': tmpID, 
			'fields': 'EMAIL':[], 
			'params': { "REGISTER_SONET_EVENT": "Y"}
	}
)

**Comment by yarbshk** [comment]
hi, @sbatov !

first, questions related to querying I recommend you to ask directly on [Bitrix24 forum](https://www.bitrix24.com/support/forum/forum45/).  use this issue tracker for issues related to pybitrix24 (for example bugs, ideas, design questions, etc.), please.

... and now back to your question. explicitly set `None` as value for all emails you want to remove from the list:

```python
bx24.call_webhook(WEBHOOK, 'crm.lead.update', {
    'ID': 2,
    'fields': {
        'EMAIL': [{'ID': 4, 'VALUE': None}],
    },
    'params': {"REGISTER_SONET_EVENT": "Y"}
})
```

hope it helps!

**Comment by sbatov** [comment]
Thank you for prompt responce and sorry for overusing your expertise - i was under the impression that it's python's issue, not the Bitrix's one. If i can be useful in exchange to your advise - feel free to ask.
And - yes, it helps! Thank you!!

**Comment by yarbshk** [comment]
thanks! i'll be grateful if you [provide some short feedback](https://forms.gle/uaFzNcD61Ju4jgEf6) on the use of the library if any.

can we consider this issue closed?
